version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      bun-dependencies:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]
