services:
  app:
    image: ghcr.io/yohanesgre/lexa:${LXK_IMAGE_TAG:-staging}

  tunnel:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
