// React Doctor config (https://react.doctor/docs/configuration/config-files)
//
// `.repos/` is the vendored Effect source clone for the effect-ts skill
// (research only — pinned to the installed version, gitignored, never part of
// the build). Its findings are third-party code, not lexa; exclude it from
// scans so the CI gate and local runs only report on lexa code.
//
// `app/router.tsx` is flagged "unused-file" but it is NOT dead: it's the
// TanStack Start router entry wired in app.config.ts (the build fails without
// it — `Could not resolve entry for router entry`). No code imports it, which
// is exactly what the detector matches; the reference lives in build config,
// not imports. Documented false positive.
export default {
  ignore: {
    files: [".repos/**", "app/router.tsx",
      // Deploy commands were hard-removed from the CLI (cli-v2026.2.0, owner
      // decision). The deleted files were previously scanned by react-doctor
      // and the maintainability analyzer cannot handle removed paths (upstream
      // 0.9.13 bug — see status/rd-grind.md TOOL BUG) → ignore the ghosts.
      "cli/src/deploy.ts", "cli/src/deploy-workers.ts",
      "cli/src/deploy.test.ts", "cli/src/deploy-workers.test.ts",
      "cli/src/packed-compose.ts", "cli/src/packed-compose.test.ts",
      "cli/src/machine-process.test.ts",
      // packed.ts is GENERATED by `bun run compile:cli` (embedded Hearth daemon
      // bundle). Its insecure-crypto-risk finding is a false positive inside the
      // bundled dependency tree (a seeded PRNG for scheduling, not crypto).
      "cli/src/packed.ts",
    ],
  },
};
