/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HearthRouteImport } from './routes/hearth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugBoardRouteImport } from './routes/$slug/board'
import { Route as SlugChatRouteImport } from './routes/$slug/chat'
import { Route as SlugMilestonesRouteImport } from './routes/$slug/milestones'
import { Route as SlugSettingsRouteImport } from './routes/$slug/settings'
import { Route as SlugSwimlanesRouteImport } from './routes/$slug/swimlanes'
import { Route as SlugTasksRouteImport } from './routes/$slug/tasks'
import { Route as SettingsMeRouteImport } from './routes/settings/me'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings/workspace'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SlugWikiIndexRouteImport } from './routes/$slug/wiki/index'
import { Route as SlugWikiPageSlugRouteImport } from './routes/$slug/wiki/$pageSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as SettingsProjectProjectIdRouteImport } from './routes/settings/project.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HearthRoute = HearthRouteImport.update({
  id: '/hearth',
  path: '/hearth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugBoardRoute = SlugBoardRouteImport.update({
  id: '/$slug/board',
  path: '/$slug/board',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugChatRoute = SlugChatRouteImport.update({
  id: '/$slug/chat',
  path: '/$slug/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugMilestonesRoute = SlugMilestonesRouteImport.update({
  id: '/$slug/milestones',
  path: '/$slug/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSettingsRoute = SlugSettingsRouteImport.update({
  id: '/$slug/settings',
  path: '/$slug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSwimlanesRoute = SlugSwimlanesRouteImport.update({
  id: '/$slug/swimlanes',
  path: '/$slug/swimlanes',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugTasksRoute = SlugTasksRouteImport.update({
  id: '/$slug/tasks',
  path: '/$slug/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMeRoute = SettingsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugWikiIndexRoute = SlugWikiIndexRouteImport.update({
  id: '/$slug/wiki/',
  path: '/$slug/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugWikiPageSlugRoute = SlugWikiPageSlugRouteImport.update({
  id: '/$slug/wiki/$pageSlug',
  path: '/$slug/wiki/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProjectProjectIdRoute =
  SettingsProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/hearth': typeof HearthRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/$slug/milestones': typeof SlugMilestonesRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/swimlanes': typeof SlugSwimlanesRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/settings/me': typeof SettingsMeRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/share/$token': typeof ShareTokenRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/wiki/$pageSlug': typeof SlugWikiPageSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/project/$projectId': typeof SettingsProjectProjectIdRoute
  '/$slug/wiki/': typeof SlugWikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/hearth': typeof HearthRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/$slug/milestones': typeof SlugMilestonesRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/swimlanes': typeof SlugSwimlanesRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/settings/me': typeof SettingsMeRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/share/$token': typeof ShareTokenRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/wiki/$pageSlug': typeof SlugWikiPageSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/project/$projectId': typeof SettingsProjectProjectIdRoute
  '/$slug/wiki': typeof SlugWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/hearth': typeof HearthRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/$slug/milestones': typeof SlugMilestonesRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/swimlanes': typeof SlugSwimlanesRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/settings/me': typeof SettingsMeRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/share/$token': typeof ShareTokenRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/wiki/$pageSlug': typeof SlugWikiPageSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/project/$projectId': typeof SettingsProjectProjectIdRoute
  '/$slug/wiki/': typeof SlugWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/hearth'
    | '/invite'
    | '/login'
    | '/set-password'
    | '/settings'
    | '/setup'
    | '/$slug/board'
    | '/$slug/chat'
    | '/$slug/milestones'
    | '/$slug/settings'
    | '/$slug/swimlanes'
    | '/$slug/tasks'
    | '/settings/me'
    | '/settings/team'
    | '/settings/workspace'
    | '/share/$token'
    | '/$slug/'
    | '/$slug/wiki/$pageSlug'
    | '/api/auth/$'
    | '/settings/project/$projectId'
    | '/$slug/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/hearth'
    | '/invite'
    | '/login'
    | '/set-password'
    | '/settings'
    | '/setup'
    | '/$slug/board'
    | '/$slug/chat'
    | '/$slug/milestones'
    | '/$slug/settings'
    | '/$slug/swimlanes'
    | '/$slug/tasks'
    | '/settings/me'
    | '/settings/team'
    | '/settings/workspace'
    | '/share/$token'
    | '/$slug'
    | '/$slug/wiki/$pageSlug'
    | '/api/auth/$'
    | '/settings/project/$projectId'
    | '/$slug/wiki'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/hearth'
    | '/invite'
    | '/login'
    | '/set-password'
    | '/settings'
    | '/setup'
    | '/$slug/board'
    | '/$slug/chat'
    | '/$slug/milestones'
    | '/$slug/settings'
    | '/$slug/swimlanes'
    | '/$slug/tasks'
    | '/settings/me'
    | '/settings/team'
    | '/settings/workspace'
    | '/share/$token'
    | '/$slug/'
    | '/$slug/wiki/$pageSlug'
    | '/api/auth/$'
    | '/settings/project/$projectId'
    | '/$slug/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  HearthRoute: typeof HearthRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SlugBoardRoute: typeof SlugBoardRoute
  SlugChatRoute: typeof SlugChatRoute
  SlugMilestonesRoute: typeof SlugMilestonesRoute
  SlugSettingsRoute: typeof SlugSettingsRoute
  SlugSwimlanesRoute: typeof SlugSwimlanesRoute
  SlugTasksRoute: typeof SlugTasksRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugWikiPageSlugRoute: typeof SlugWikiPageSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SlugWikiIndexRoute: typeof SlugWikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearth': {
      id: '/hearth'
      path: '/hearth'
      fullPath: '/hearth'
      preLoaderRoute: typeof HearthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/board': {
      id: '/$slug/board'
      path: '/$slug/board'
      fullPath: '/$slug/board'
      preLoaderRoute: typeof SlugBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/chat': {
      id: '/$slug/chat'
      path: '/$slug/chat'
      fullPath: '/$slug/chat'
      preLoaderRoute: typeof SlugChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/milestones': {
      id: '/$slug/milestones'
      path: '/$slug/milestones'
      fullPath: '/$slug/milestones'
      preLoaderRoute: typeof SlugMilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/settings': {
      id: '/$slug/settings'
      path: '/$slug/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof SlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/swimlanes': {
      id: '/$slug/swimlanes'
      path: '/$slug/swimlanes'
      fullPath: '/$slug/swimlanes'
      preLoaderRoute: typeof SlugSwimlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/tasks': {
      id: '/$slug/tasks'
      path: '/$slug/tasks'
      fullPath: '/$slug/tasks'
      preLoaderRoute: typeof SlugTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/me': {
      id: '/settings/me'
      path: '/me'
      fullPath: '/settings/me'
      preLoaderRoute: typeof SettingsMeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/wiki/': {
      id: '/$slug/wiki/'
      path: '/$slug/wiki'
      fullPath: '/$slug/wiki/'
      preLoaderRoute: typeof SlugWikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/wiki/$pageSlug': {
      id: '/$slug/wiki/$pageSlug'
      path: '/$slug/wiki/$pageSlug'
      fullPath: '/$slug/wiki/$pageSlug'
      preLoaderRoute: typeof SlugWikiPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/project/$projectId': {
      id: '/settings/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/settings/project/$projectId'
      preLoaderRoute: typeof SettingsProjectProjectIdRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsMeRoute: typeof SettingsMeRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
  SettingsProjectProjectIdRoute: typeof SettingsProjectProjectIdRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMeRoute: SettingsMeRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
  SettingsProjectProjectIdRoute: SettingsProjectProjectIdRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  HearthRoute: HearthRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  SlugBoardRoute: SlugBoardRoute,
  SlugChatRoute: SlugChatRoute,
  SlugMilestonesRoute: SlugMilestonesRoute,
  SlugSettingsRoute: SlugSettingsRoute,
  SlugSwimlanesRoute: SlugSwimlanesRoute,
  SlugTasksRoute: SlugTasksRoute,
  ShareTokenRoute: ShareTokenRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugWikiPageSlugRoute: SlugWikiPageSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SlugWikiIndexRoute: SlugWikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
