/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugBoardRouteImport } from './routes/$slug/board'
import { Route as SlugSettingsRouteImport } from './routes/$slug/settings'
import { Route as SlugTasksRouteImport } from './routes/$slug/tasks'
import { Route as SlugWikiIndexRouteImport } from './routes/$slug/wiki/index'
import { Route as SlugWikiPageSlugRouteImport } from './routes/$slug/wiki/$pageSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugBoardRoute = SlugBoardRouteImport.update({
  id: '/$slug/board',
  path: '/$slug/board',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSettingsRoute = SlugSettingsRouteImport.update({
  id: '/$slug/settings',
  path: '/$slug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugTasksRoute = SlugTasksRouteImport.update({
  id: '/$slug/tasks',
  path: '/$slug/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugWikiIndexRoute = SlugWikiIndexRouteImport.update({
  id: '/$slug/wiki/',
  path: '/$slug/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugWikiPageSlugRoute = SlugWikiPageSlugRouteImport.update({
  id: '/$slug/wiki/$pageSlug',
  path: '/$slug/wiki/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/wiki/$pageSlug': typeof SlugWikiPageSlugRoute
  '/$slug/wiki/': typeof SlugWikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/wiki/$pageSlug': typeof SlugWikiPageSlugRoute
  '/$slug/wiki': typeof SlugWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/wiki/$pageSlug': typeof SlugWikiPageSlugRoute
  '/$slug/wiki/': typeof SlugWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forge'
    | '/settings'
    | '/setup'
    | '/$slug/board'
    | '/$slug/settings'
    | '/$slug/tasks'
    | '/$slug/'
    | '/$slug/wiki/$pageSlug'
    | '/$slug/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forge'
    | '/settings'
    | '/setup'
    | '/$slug/board'
    | '/$slug/settings'
    | '/$slug/tasks'
    | '/$slug'
    | '/$slug/wiki/$pageSlug'
    | '/$slug/wiki'
  id:
    | '__root__'
    | '/'
    | '/forge'
    | '/settings'
    | '/setup'
    | '/$slug/board'
    | '/$slug/settings'
    | '/$slug/tasks'
    | '/$slug/'
    | '/$slug/wiki/$pageSlug'
    | '/$slug/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgeRoute: typeof ForgeRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SlugBoardRoute: typeof SlugBoardRoute
  SlugSettingsRoute: typeof SlugSettingsRoute
  SlugTasksRoute: typeof SlugTasksRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugWikiPageSlugRoute: typeof SlugWikiPageSlugRoute
  SlugWikiIndexRoute: typeof SlugWikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/board': {
      id: '/$slug/board'
      path: '/$slug/board'
      fullPath: '/$slug/board'
      preLoaderRoute: typeof SlugBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/settings': {
      id: '/$slug/settings'
      path: '/$slug/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof SlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/tasks': {
      id: '/$slug/tasks'
      path: '/$slug/tasks'
      fullPath: '/$slug/tasks'
      preLoaderRoute: typeof SlugTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/wiki/': {
      id: '/$slug/wiki/'
      path: '/$slug/wiki'
      fullPath: '/$slug/wiki/'
      preLoaderRoute: typeof SlugWikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/wiki/$pageSlug': {
      id: '/$slug/wiki/$pageSlug'
      path: '/$slug/wiki/$pageSlug'
      fullPath: '/$slug/wiki/$pageSlug'
      preLoaderRoute: typeof SlugWikiPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgeRoute: ForgeRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SlugBoardRoute: SlugBoardRoute,
  SlugSettingsRoute: SlugSettingsRoute,
  SlugTasksRoute: SlugTasksRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugWikiPageSlugRoute: SlugWikiPageSlugRoute,
  SlugWikiIndexRoute: SlugWikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
