/**
 * Compile lexa-cli into the standalone prod binary.
 *
 *   bun run compile:cli
 *
 * Bundles the Forge daemon (scripts/forge/daemon.ts imports shared modules) —
 * the bundled JS is embedded into scripts/cli/packed.ts so the compiled
 * binary can write it to ~/.local/share/lexa-forge/daemon.js — then runs
 * `bun build --compile` → bin/lexa-cli.
 *
 * Install/uninstall:
 *   bun run install:cli      → ~/.local/bin/lexa-cli (prod binary)
 *   bun run uninstall:cli    → removes it
 *   bun run install:cli-dev  → ~/.local/bin/lexa-cli-dev (shim → live repo
 *                              source via bun; never overwrites the prod name)
 *   bun run uninstall:cli-dev → removes the dev shim
 *
 * Note: this regenerates scripts/cli/packed.ts with the embedded daemon
 * source. The committed state is an empty stub so `bun run lexa-cli-dev`
 * keeps copying daemon.ts fresh from disk — restore it before committing:
 * `git checkout scripts/cli/packed.ts`.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const daemonPath = join(root, "scripts", "forge", "daemon.ts");
const packedPath = join(root, "scripts", "cli", "packed.ts");
const outfile = join(root, "bin", "lexa-cli");
const bundlePath = join(root, "bin", "daemon-bundle.js");

if (!existsSync(daemonPath)) {
  console.error(`  Daemon source missing at ${daemonPath}`);
  process.exit(1);
}

// The daemon imports shared modules (shared/forge-log.ts) — bundle it so the
// embedded copy is self-contained on machines without the repo.
mkdirSync(join(root, "bin"), { recursive: true });
const bundle = spawnSync("bun", ["build", "--target=bun", "--outfile", bundlePath, daemonPath], { stdio: "pipe" });
if (bundle.status !== 0) {
  console.error(`  Daemon bundle failed: ${bundle.stderr?.toString().slice(0, 500)}`);
  process.exit(1);
}
const source = readFileSync(bundlePath, "utf-8");
rmSync(bundlePath, { force: true });
writeFileSync(
  packedPath,
  `// Generated by \`bun run compile:cli\` — embeds the bundled Forge daemon (the\n` +
    `// listener writes it to ~/.local/share/lexa-forge/daemon.js and runs it).\n` +
    `// Stub state (empty) = running from source; the daemon is bundled from disk.\n` +
    `export const DAEMON_SOURCE = ${JSON.stringify(source)};\n`,
);

mkdirSync(join(root, "bin"), { recursive: true });
const result = spawnSync(
  "bun",
  ["build", "--compile", "--minify", "--outfile", outfile, join(root, "scripts", "cli", "index.ts")],
  { stdio: "inherit" },
);
if (result.status !== 0) process.exit(result.status ?? 1);

const size = (await Bun.file(outfile).stat()).size;
console.log(`  Compiled → ${outfile} (${(size / 1024 / 1024).toFixed(1)} MB)`);
console.log(`  Install prod:  bun run install:cli      (→ ~/.local/bin/lexa-cli)`);
console.log(`  Install dev:   bun run install:cli-dev  (→ ~/.local/bin/lexa-cli-dev)`);
