/**
 * Compile lexa-cli into the standalone prod binary.
 *
 *   bun run compile:cli
 *
 * Bundles the Forge daemon (forge/daemon.ts imports shared modules) —
 * the bundled JS is embedded into cli/src/packed.ts so the compiled
 * binary can write it to ~/.local/share/lexa-forge/daemon.js — then runs
 * `bun build --compile` → bin/lexa-cli.
 *
 * The compiled binary is distributed via `scripts/install-cli.sh`
 * (downloads the GitHub release asset) — there is no repo install step.
 *
 * Install/uninstall (dev shim only):
 *   bun run install:cli-dev  → ~/.local/bin/lexa-cli-dev (shim → live repo
 *                              source via bun; never overwrites the prod name)
 *   bun run uninstall:cli-dev → removes the dev shim
 *
 * Note: this regenerates cli/src/packed.ts (daemon embed) and cli/src/packed-compose.ts
 * (deploy compose files) with real content. The committed state is a stub for
 * both — restore them before committing:
 * `git checkout cli/src/packed.ts cli/src/packed-compose.ts`.
 * The CLI version is NOT regenerated: it is read from cli/package.json
 * (static, see cli/src/version.ts).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { gzipSync } from "node:zlib";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const daemonPath = join(root, "forge", "daemon.ts");
const packedPath = join(root, "cli", "src", "packed.ts");
const composePackPath = join(root, "cli", "src", "packed-compose.ts");
const outfile = join(root, "bin", "lexa-cli");
const bundlePath = join(root, "bin", "daemon-bundle.js");

if (!existsSync(daemonPath)) {
  console.error(`  Daemon source missing at ${daemonPath}`);
  process.exit(1);
}

// The daemon imports shared modules (shared/forge-log.ts) — bundle it so the
// embedded copy is self-contained on machines without the repo.
mkdirSync(join(root, "bin"), { recursive: true });
const bundle = spawnSync("bun", ["build", "--target=bun", "--outfile", bundlePath, daemonPath], { stdio: "pipe" });
if (bundle.status !== 0) {
  console.error(`  Daemon bundle failed: ${bundle.stderr?.toString().slice(0, 500)}`);
  process.exit(1);
}
const source = readFileSync(bundlePath, "utf-8");
rmSync(bundlePath, { force: true });
writeFileSync(
  packedPath,
  `// Generated by \`bun run compile:cli\` — embeds the bundled Forge daemon (the\n` +
    `// listener writes it to ~/.local/share/lexa-forge/daemon.js and runs it).\n` +
    `// Stub state (empty) = running from source; the daemon is bundled from disk.\n` +
    `export const DAEMON_SOURCE = ${JSON.stringify(source)};\n`,
);

// ── Deploy compose embed ──
// `lexa-cli deploy` pulls a prebuilt image (ghcr.io) on a clean machine — it
// never builds from source. The compose files ARE the deploy contract, so
// they're embedded here (few KB) and materialized to the deploy dir at
// deploy time. No repo checkout is ever needed.
const COMPOSE_FILES_LIST = ["docker-compose.yml", "docker-compose.staging.yml", "docker-compose.prod.yml"];
const composePacked = COMPOSE_FILES_LIST.filter((f) => existsSync(join(root, f)))
  .map((f) => `${JSON.stringify(f)}:${JSON.stringify(gzipSync(readFileSync(join(root, f))).toString("base64"))}`)
  .join(",\n");
writeFileSync(
  composePackPath,
  `// Generated by \`bun run compile:cli\` — embeds the Docker compose files so\n` +
    `// \`lexa-cli deploy\` runs on a clean machine with no repo checkout. Stub state\n` +
    `// (empty) = running from source; deploy materializes the embedded copies.\n` +
    `export const COMPOSE_FILES: Record<string, string> = {\n${composePacked}\n};\n`,
);
console.log(`  Embedded deploy compose: ${COMPOSE_FILES_LIST.length} files`);

mkdirSync(join(root, "bin"), { recursive: true });
const result = spawnSync(
  "bun",
    ["build", "--compile", "--minify", "--outfile", outfile, join(root, "cli", "src", "index.ts")],
  { stdio: "inherit" },
);
if (result.status !== 0) process.exit(result.status ?? 1);

const size = (await Bun.file(outfile).stat()).size;
console.log(`  Compiled → ${outfile} (${(size / 1024 / 1024).toFixed(1)} MB)`);
console.log(`  Distribute:  scripts/install-cli.sh (downloads the GitHub release asset)`);
console.log(`  Dev shim:    bun run install:cli-dev  (→ ~/.local/bin/lexa-cli-dev)`);
