// Pure helper for scripts/compile-cli.ts: the committed packed.ts stub and the
// embed generator. Kept out of the compile script so test:cli covers the
// `$`-pattern regression without shelling out to `bun run compile:cli`.
export const PACKED_STUB = `// Generated by \`bun run compile:cli\` — embeds the bundled Hearth daemon (the
// listener writes it to ~/.local/share/lexa-hearth/daemon.js and runs it).
// Stub state (empty) = running from source; the daemon is bundled from disk.
export const DAEMON_SOURCE = "";
`;

const STUB_MARKER = 'export const DAEMON_SOURCE = "";';

// Function replacer: String.prototype.replace expands `$$`, `$&`, `` $` ``,
// `$'` and `$n` in a *string* replacement — the bundled daemon contains
// Effect's escapeRegExp body (`"$&"`), which corrupted the embed. A replacer
// function's return value is inserted verbatim, so the JSON survives intact.
export const packedEmbed = (source: string): string =>
  PACKED_STUB.replace(STUB_MARKER, () => `export const DAEMON_SOURCE = ${JSON.stringify(source)};`);
