// Generated by `bun run compile:cli` — embeds the bundled Hearth daemon (the
// listener writes it to ~/.local/share/lexa-hearth/daemon.js and runs it).
// Stub state (empty) = running from source; the daemon is bundled from disk.
export const DAEMON_SOURCE = "";
