// Generated by `bun run compile:cli` — embeds the Docker compose files so
// `lexa-cli deploy` runs on a clean machine with no repo checkout. Stub state
// (empty) = running from source; deploy materializes the embedded copies.
export const COMPOSE_FILES: Record<string, string> = {

};
